project_name: procguard
version: 2

before:
  hooks:
    - dir: wails-app
      cmd: make build VERSION={{.Version}}

builds:
  - id: ProcGuard
    builder: prebuilt
    binary: wails-app/build/bin/ProcGuard
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Ext }}"
    format: binary
    files:
      - src: 'wails-app/build/bin/ProcGuard.exe'
        dst: ProcGuard.exe

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: infraflakes
    name: procguard
